### PR TITLE
Add "if __name__ == __main__" to script for more ways to execute it.

### PR DESCRIPTION
**Pull request by carlosperate**
This way we can run microfs using with these two other methods:

```
python -m microfs ...
python microfs.py ...
```

### CODE REVIEW

**Comment by carlosperate** [comment]
@ntoll this can also be merge if you like

**Comment by ntoll** [comment]
Conflicts..! ;-)

**Comment by carlosperate** [comment]
Rebased and fixed 👍

**Comment by ntoll** [comment]
Thank you..!

**Pull request merged**
